name: Build, Test and Deploy React Application

# Controls when the action will run. 
on:
  # Listen to a repository dispatch event by the name of `dispatch-event`
  repository_dispatch:
    types: [dispatch-event]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    permissions:                # Job-level permissions configuration starts here
        contents: write           # 'write' access to repository contents
        pull-requests: write      # 'write' access to pull requests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: npm ci and test
        run: |
          npm ci
          npm test  
        env: 
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      - name: Build the stack react
        run: |
          docker compose --version
          docker compose up -d
        env: 
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      - name: Run e2e tests with cypress
        uses: cypress-io/github-action@v6
      - name: Stop the stack react
        run: docker compose down
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build and docs
        run: |
          npm run jsdoc
          npm run build --if-present
        env: 
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      - name: build package on NPM ðŸ“¦
        run: pm run build-npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish package on NPM ðŸ“¦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: build
          if-no-files-found: error

  # Deploy job
  deploy:
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    # Add a dependency to the build job
    needs: build_test
    # Specify runner + deployment step
    steps:
    #  - name: Set env
    #    run: |
    #      npm i -g semver
    #      echo "GITHUB_VERSION_BUILD=$(echo $(semver 0.1.1 -i prerelease --preid ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}))" >> $GITHUB_ENV
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
